/** @type {import('tailwindcss').Config} */
module.exports = {
    // NativeWind web syncs color scheme via class on <html>; "media" throws on manual set.
    darkMode: 'class',
    content: [
        './App.{js,jsx,ts,tsx}',
        './src/**/*.{js,jsx,ts,tsx}',
        './screens/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
        './navigation/**/*.{js,jsx,ts,tsx}',
    ],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#60A5FA',
                    dark: '#3B82F6',
                    light: '#93C5FD',
                    'extra-light': '#DBEAFE',
                },
                success: '#10B981',
                warning: '#F59E0B',
                error: '#EF4444',
                info: '#60A5FA',
                gray: {
                    50: '#F9FAFB',
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#111827',
                },
                background: {
                    primary: '#FFFFFF',
                    secondary: '#F8FAFC',
                    tertiary: '#F3F4F6',
                },
                text: {
                    primary: '#111827',
                    secondary: '#6B7280',
                    tertiary: '#9CA3AF',
                    inverse: '#FFFFFF',
                },
                border: {
                    DEFAULT: '#E5E7EB',
                    dark: '#D1D5DB',
                    light: '#F3F4F6',
                },
            },
            fontSize: {
                xs: '12px',
                sm: '14px',
                base: '16px',
                lg: '18px',
                xl: '20px',
                '2xl': '24px',
                '3xl': '30px',
                '4xl': '36px',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '12px',
                base: '16px',
                lg: '20px',
                xl: '24px',
                '2xl': '32px',
                '3xl': '40px',
                '4xl': '48px',
                '5xl': '64px',
            },
            borderRadius: {
                none: '0',
                sm: '4px',
                md: '8px',
                lg: '12px',
                xl: '16px',
                '2xl': '20px',
                '3xl': '24px',
                full: '9999px',
            },
            boxShadow: {
                sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
                md: '0 2px 4px rgba(0, 0, 0, 0.1)',
                lg: '0 4px 8px rgba(0, 0, 0, 0.15)',
                xl: '0 8px 16px rgba(0, 0, 0, 0.2)',
            },
        },
    },
    plugins: [],
};
