/**
 * withAndroidSplashFullBleed
 *
 * Android 12+ applies the adaptive-icon shape mask to windowSplashScreenAnimatedIcon,
 * which clips the wallet logo's rounded corners.
 *
 * Fix: move the logo into windowSplashScreenBackground as a layer-list drawable.
 * Background drawables are never masked — the logo appears at full fidelity.
 * The animated-icon slot gets a transparent shape so no masking artifact shows.
 *
 * Must be declared AFTER expo-splash-screen in app.json plugins so it runs after
 * expo-splash-screen has already generated splashscreen_logo.png and set up styles.xml.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

const SPLASH_FULLSCREEN_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Full-bleed splash background: white fill + centered logo.
  Using layer-list here (not windowSplashScreenAnimatedIcon) because Android 12+
  masks the animated-icon to the adaptive-icon shape, clipping rounded corners.
  Background drawables are displayed without any masking.
-->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <color android:color="#ffffff"/>
    </item>
    <!--
      splashscreen_logo.png is a 288dp × 288dp canvas generated by expo-splash-screen
      with the logo (imageWidth dp) centered inside.  Display it at 288dp centered
      so it renders at exactly the right size with no up/downscaling.
    -->
    <item
        android:width="288dp"
        android:height="288dp"
        android:gravity="center">
        <bitmap
            android:src="@drawable/splashscreen_logo"
            android:gravity="fill"
            android:antialias="true"
            android:filter="true"/>
    </item>
</layer-list>
`;

const TRANSPARENT_ICON_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Transparent placeholder for windowSplashScreenAnimatedIcon.
  Android still requires an icon drawable; a fully-transparent shape is invisible
  and prevents the system from falling back to the (masked) launcher icon.
-->
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#00000000"/>
</shape>
`;

function withAndroidSplashFullBleed(config) {
    // ── Phase 1: write drawable XML files ──────────────────────────────────
    config = withDangerousMod(config, [
        'android',
        async (config) => {
            const drawablePath = path.join(
                config.modRequest.platformProjectRoot,
                'app/src/main/res/drawable',
            );
            fs.mkdirSync(drawablePath, { recursive: true });

            fs.writeFileSync(
                path.join(drawablePath, 'splash_fullscreen.xml'),
                SPLASH_FULLSCREEN_XML,
            );
            fs.writeFileSync(
                path.join(drawablePath, 'splash_icon_transparent.xml'),
                TRANSPARENT_ICON_XML,
            );

            return config;
        },
    ]);

    // ── Phase 2: patch styles.xml via withDangerousMod ────────────────────
    // withAndroidStyles runs before expo-splash-screen's file writes and gets
    // overwritten.  withDangerousMod runs AFTER all base mods, so it reliably
    // overwrites whatever expo-splash-screen wrote.
    config = withDangerousMod(config, [
        'android',
        async (config) => {
            const stylesPath = path.join(
                config.modRequest.platformProjectRoot,
                'app/src/main/res/values/styles.xml',
            );

            let content = fs.readFileSync(stylesPath, 'utf-8');

            // Swap background to our layer-list drawable (never masked by Android).
            content = content.replace(
                /(<item\s+name="windowSplashScreenBackground">)[^<]*(<\/item>)/,
                '$1@drawable/splash_fullscreen$2',
            );

            // Replace animated-icon with transparent shape so nothing gets masked.
            content = content.replace(
                /(<item\s+name="windowSplashScreenAnimatedIcon">)[^<]*(<\/item>)/,
                '$1@drawable/splash_icon_transparent$2',
            );

            // Remove icon_preferred — without it Android won't force the icon circle.
            content = content.replace(
                /\s*<item\s+name="android:windowSplashScreenBehavior">[^<]*<\/item>/g,
                '',
            );

            fs.writeFileSync(stylesPath, content, 'utf-8');
            return config;
        },
    ]);

    return config;
}

module.exports = withAndroidSplashFullBleed;
